### ISSUE TITLE
add long term helloword examples in the doc

### ISSUE THREAD

**Issue by mga-chka** [yohannj/clickhouse-polyglot#1]
Hello yohann
Imho, if you want to get traction, you should put a few examples of what this project is supposed to do once it's advanced enough.
In its current state, it's a bit complex to follow unless for the rare people you already talked about this project in the past (like me).

**Comment by yohannj** [comment]
Hey @mga-chka 

You're totally right.
I just updated the readme ([commit](https://github.com/yohannj/clickhouse-polyglot/commit/b710a6a226c67a142a0f1d9f9a16d89af8a5d153)) to include a part talking about it, including schemas to better grasps things:
```
Project objectives
    Allow services in different languages to build a query together
    Low overhead DSL
    Query introspection
    Security by design
```

I also noticed that I forgot Github's markdown renderer behaves differently from what i use in vscode.
I took the opportunity to fix all the new lines that should make the README more readable.


Was it what you had in mind, or do you feel it's still missing the point?
